# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-10 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('status', multiselectfield.db.fields.MultiSelectField(choices=[('m', 'Man'), ('w', 'Woman'), ('c', 'Child'), ('d', 'Draft')], max_length=7)),
                ('image_url', models.CharField(default='nourl', max_length=500)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, height_field='height_field', null=True, upload_to='images/brands/', width_field='width_field')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('status', multiselectfield.db.fields.MultiSelectField(choices=[('m', 'Man'), ('w', 'Woman'), ('c', 'Child'), ('d', 'Draft')], max_length=7)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ('title',),
                'verbose_name_plural': 'categories',
                'verbose_name': 'category',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(unique=True)),
                ('thumb_url', models.CharField(blank=True, max_length=500, null=True)),
                ('thumb', models.FileField(blank=True, null=True, upload_to='images/products/%Y/%m/%d')),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'DOLLAR'), ('EUR', 'EURO'), ('TJS', 'SOMONI'), ('RUB', 'RUSSIAN RUBLE'), ('TRY', 'TURKISH LIRA')], default='TJS', max_length=5)),
                ('is_published', models.BooleanField(default=False)),
                ('in_stock', models.PositiveIntegerField(default=1)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Brands')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Category')),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='images/products/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Usage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('status', multiselectfield.db.fields.MultiSelectField(choices=[('m', 'Man'), ('w', 'Woman'), ('c', 'Child'), ('d', 'Draft')], max_length=7)),
                ('description', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='usage_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Usage'),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set([('id', 'slug')]),
        ),
    ]
